name: Dev CI/CD - SonarCloud Quality Gate.

on:
  push:
    branches: ["dev", "feature/**"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:
    inputs:
      run_deploy:
        description: "Deploy to Dev environment"
        type: boolean
        required: false
        default: false

permissions:
  contents: read
  packages: write
  id-token: write
  pull-requests: write

env:
  REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonar:
    name: SonarCloud Scan and Quality Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build and Push Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: api-gateway
            context: StockWiz/api-gateway
            dockerfile: StockWiz/api-gateway/Dockerfile
          - name: product-service
            context: StockWiz/product-service
            dockerfile: StockWiz/product-service/Dockerfile
          - name: inventory-service
            context: StockWiz/inventory-service
            dockerfile: StockWiz/inventory-service/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        if: ${{ hashFiles(matrix.dockerfile) != '' }}
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.name }}
          tags: |
            type=raw,value=dev-${{ github.sha }}
            type=raw,value=dev-latest

      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ hashFiles(matrix.dockerfile) != '' }}
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  bootstrap:
    name: Bootstrap infrastructure
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (bootstrap)
        working-directory:  iac/bootstrap
        run: terraform init

      - name: Terraform Apply (bootstrap)
        working-directory:  iac/bootstrap
        run: terraform apply -auto-approve

  deploy_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs:  bootstrap
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/dev' || (github.event_name == 'workflow_dispatch' && inputs.run_deploy) ||  failure()  }}
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: List Service Discovery Namespaces
        run: aws servicediscovery list-namespaces

      - name: Terraform Init
        working-directory: iac/environments/dev
        run: terraform init

      - name: Terraform Apply
        working-directory: iac/environments/dev
        run: |
          terraform apply -auto-approve

  load_tests:
    name: Run k6 load tests
    runs-on: ubuntu-latest
    needs: deploy_dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          curl -s https://api.github.com/repos/grafana/k6/releases/latest \
            | grep "browser_download_url.*linux-amd64.deb" \
            | cut -d '"' -f 4 \
            | xargs curl -L -o k6.deb
          sudo dpkg -i k6.deb

      - name: Run Product Load Test
        run: |
          k6 run Tests/Load/api-gateway-load-test-products.js

      - name: Run Product Load Test
        run: |
          k6 run Tests/Load/api-gateway-product-detail-load-test.js


  cleanup_after_test:
    name: Cleanup on Failure
    runs-on: ubuntu-latest
    needs: load_tests
    if: ${{ failure() }}   # Se ejecuta solo si alguno de los jobs anteriores falla
    steps:
      - name: Checkout repository
        #uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Terraform dev
        working-directory: iac/environments/dev
        run: terraform init

      - name: Destroy deploy dev infrastructure
        working-directory: iac/environments/dev
        run: terraform destroy -auto-approve


    
